# Generated by Django 2.2.3 on 2019-08-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='date',
            field=models.CharField(default='', max_length=15),
        ),
    ]
